version: '3'

services:
  db:
    image: shoushaa/flask-db
    ports:
      - "30001:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: shoushaa/flask-app
    ports:
      - "5000:5000"
    links:
      - db