version: '3'

services:
  db:
    image: mysql
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - ./db:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: ./app
    ports:
      - "5000:5000"
    links:
      - db