apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: shoushaa/flask-app
        ports:
        - containerPort: 5000      
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10    
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
                
        env:
        - name: MYSQL_DATABASE_PASSWORD
          value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: ingress-nginx
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 5000
