---
- name: Install jenkins
  hosts: all
  become: true
  remote_user: ec2-user
  tasks:
  - name: install java
    shell: sudo amazon-linux-extras install java-openjdk11 -y 
    args:
      creates: /usr/bin/java

  - name: yum update
    yum:
      name: '*'
      state: latest
      lock_timeout: 180

  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: Jenkins Skip Wizard login for MI
    lineinfile:
      dest=/etc/sysconfig/jenkins
      regexp=^JAVA_ARGS=
      line='JAVA_ARGS="-Djenkins.install.runSetupWizard=false"'
    become: true

  - name: Create initialization scripts directory
    file: path=/var/lib/jenkins/init.groovy.d
          state=directory
          owner=jenkins
          group=jenkins
          mode=0775

  - name: Add initialization script to setup basic security
    template: src=basic-security.groovy
              dest=/var/lib/jenkins/init.groovy.d/security.groovy

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
    async: 200
    ignore_errors: yes
